name: Pingo frontend

on:
  push:
    branches:
      - main

jobs:
  web-deploy:
    name: Deploy Angular App
    runs-on: ubuntu-latest

    steps:
      - name: Get latest code
        uses: actions/checkout@v2.3.2

      - name: Build Docker image
        run: docker build -t profilsearch_front .

      - name: Push to GitHub Packages of organization
        uses: docker/build-push-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          repository: univ-smb-m1-isc-2022/pingo_frontend/main
          tags: latest
